cloud:
  aws:
    credentials:
      access-key: 
      secret-key:
    region:
      auto: false
      static: us-east-1
      use-default-aws-region-chain: true
    stack:
      auto: false

application:
  bucket:
    name: crm-erbilcolak


spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: ${MAX_FILE_SIZE:5MB}
      max-request-size: ${MAX_REQUEST_SIZE:10MB}


server:
  port: 8080
