package com.callcentercrm.www.enums;

public enum ReasonForReject {

    DOCUMENT_NOT_ID,
    DOCUMENT_NOT_DRIVING_LICENSE,
    DOCUMENT_NOT_PASSPORT,
    DOCUMENT_NOT_BILL,
    DOCUMENT_NOT_ADDRESS_VALIDATION,
    DOCUMENT_EXPIRED,
    DOCUMENT_AND_USER_NOT_MATCHING,
    DOCUMENT_IS_FLU,
    DOCUMENT_MISSING,

    TRANSFER_USER_NOT_MATCHING,
    TRANSFER_DISAPPROVED,
    TRANSFER_

}
